services:
  # Backend (Spring Boot)
  - type: web
    name: backend
    runtime: docker
    repo: https://github.com/NTAF8891/site-e-commerce-avec-IA
    rootDir: backend
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        value: jdbc:postgresql://dpg-d6eqrlp5pdvs73d2sgh0-a/shop_data_rvq9
      - key: DB_USERNAME
        value: shop_data_rvq9_user
      - key: DB_PASSWORD
        value: nT7bQ1mwUpUdBkOOHA7FDZqW9IkRz17d
      - key: STRIPE_SECRET_KEY
        sync: false

  # Frontend (React/Vite)
  - type: static
    name: frontend
    runtime: node
    repo: https://github.com/NTAF8891/site-e-commerce-avec-IA
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: backend
          property: url
